version: '3.2'
services:
    postgres:
        container_name: postgres
        build: ./postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: docker
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        ports:
            - 5432:5432